services:
  postgres:
    container_name: my-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: yippy
      POSTGRES_PASSWORD: Yippy!1234
      POSTGRES_DB: identity
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    container_name: my-rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  redis:
    container_name: my-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data: